include $(THEOS)/makefiles/common.mk

BUNDLE_NAME = RoundyDockPrefs
RoundyDockPrefs_FILES = RoundyDockPrefs.xm
RoundyDockPrefs_INSTALL_PATH = /Library/PreferenceBundles
RoundyDockPrefs_CFLAGS = -fobjc-arc
RoundyDockPrefs_FRAMEWORKS = UIKit
RoundyDockPrefs_PRIVATE_FRAMEWORKS = Preferences

include $(THEOS_MAKE_PATH)/bundle.mk
